import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Intro from '../components/Intro'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials';
import {data} from '../data';

export default function Home({services}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Agency App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Services services={services} />
      <Testimonials />
    </div>
  )
}

export const getStaticProps = () => {
  const services = data;
  return {
    props: { services },
  };
};
